zeebe:
  broker:
    gateway:
      enable: false

    network:
      advertisedHost: zeebe0
      commandApi:
        port: 26501
      internalApi:
        port: 26502
      monitoringApi:
        port: 9600

    cluster:
      clusterName: zeebe-cluster
      clusterSize: 3
      partitionsCount: 3
      replicationFactor: 3
      nodeId: 0
      initialContactPoints:
        - zeebe0:26502
        - zeebe1:26502
        - zeebe2:26502

    data:
      snapshotPeriod: 30m
      diskUsageCommandWatermark: 0.998
      diskUsageReplicationWatermark: 0.999

    threads:
      cpuThreadCount: 2
      ioThreadCount: 2

    exporters:
      elasticsearch:
        className: io.camunda.zeebe.exporter.ElasticsearchExporter
        args:
          url: http://elasticsearch:9200
          index:
            prefix: zeebe-record
          bulk:
            size: 1
          delay: 1s
