zeebe:
  gateway:
    network:
      host: 0.0.0.0
      port: 26500
    cluster:
      clusterName: zeebe-cluster           # <– auf allen Brokern gleich setzen
      memberId: zeebe-gateway
      host: 0.0.0.0
      port: 26502
      advertisedHost: zeebe-gateway        # <– Compose-Service-Name!
      initialContactPoints:
        - zeebe0:26502
        - zeebe1:26502
        - zeebe2:26502
    longPolling:
      enabled: true
    multiTenancy:
      enabled: false