zeebe:
  gateway:
    network:
      host: 0.0.0.0
      port: 26500
    cluster:
      memberId: zeebe-gateway
      host: 0.0.0.0
      port: 26502
      initialContactPoints:
        - zeebe0:26502
        - zeebe1:26502
        - zeebe2:26502
    longPolling:
      enabled: true
    multiTenancy:
      enabled: false